### ISSUE TITLE
Department page for Admin

### ISSUE THREAD

**Issue by kihan2518B** [kihan2518B/Univera#10]
Department page for Admins

**Comment by yukthi2000** [comment]
Hi @kihan2518B . I would like to make a Department page for Admins. can I get more details about it ?

**Comment by yukthi2000** [comment]
> Hey @yukthi2000, I appreciate your excitement. But currently we are redesigning our structure as well as pages so I will create some new issues accordingly. Stay tunned :).

Thank you for the update!. I’ll stay tuned for the new issues and am looking forward to contributing once they’re ready.
